FROM openjdk:17 as builder


COPY . .

RUN sed -i 's/\r$//' gradlew && chmod +x gradlew

RUN ./gradlew buildFatJar

FROM openjdk:17

COPY --from=builder /build/libs/service_identity.jar ./service_identity.jar

CMD ["java", "-jar", "service_identity.jar"]